::: ProcedureParameters

SELECT rdb$parameter_name,
(
CASE (SELECT AC.RDB$FIELD_SUB_TYPE FROM RDB$FIELDS AC WHERE rdb$field_source = AC.RDB$FIELD_NAME ) /* FIELD_SUB_TYPE*/
WHEN 0 THEN
IIF (rdb$field_source NOT CONTAINING 'RDB$', rdb$field_source,
CASE (SELECT AA.RDB$FIELD_TYPE FROM RDB$FIELDS AA WHERE rdb$field_source = AA.RDB$FIELD_NAME )
WHEN 7 THEN 'SMALLINT'
WHEN 8 THEN 'INTEGER'
WHEN 10 THEN 'FLOAT'
WHEN 12 THEN 'DATE'
WHEN 13 THEN 'TIME'
WHEN 14 THEN 'CHAR' || '(' || (SELECT RDB$FIELD_LENGTH FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 16 THEN 'BIGINT'
WHEN 27 THEN 'DOUBLE PRECISION'
WHEN 35 THEN 'TIMESTAMP'
WHEN 37 THEN 'VARCHAR' || '(' || (SELECT RDB$FIELD_LENGTH FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 261 THEN 'BLOB'
END
) /* IIF */
WHEN 1 THEN
IIF (rdb$field_source NOT CONTAINING 'RDB$', rdb$field_source,
CASE (SELECT AA.RDB$FIELD_TYPE FROM RDB$FIELDS AA WHERE rdb$field_source = AA.RDB$FIELD_NAME )
WHEN 7 THEN 'NUMERIC('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 8 THEN 'NUMERIC('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 16 THEN 'NUMERIC('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 621 THEN 'BLOB SUB_TYPE 1'
END
) /* iif */
WHEN 2 THEN
IIF (rdb$field_source NOT CONTAINING 'RDB$', rdb$field_source,
CASE (SELECT AA.RDB$FIELD_TYPE FROM RDB$FIELDS AA WHERE rdb$field_source = AA.RDB$FIELD_NAME )
WHEN 7 THEN 'DECIMAL('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 8 THEN 'DECIMAL('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
WHEN 16 THEN 'DECIMAL('|| (SELECT RDB$FIELD_PRECISION FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ',' || (SELECT RDB$FIELD_SCALE * -1 FROM RDB$FIELDS AB WHERE rdb$field_source = AB.RDB$FIELD_NAME) || ')'
END
) /* IIF */
END
) AS PARAM_TYPE
FROM rdb$procedure_parameters
WHERE rdb$procedure_name=? AND
rdb$parameter_type=? /* input or output */
ORDER BY rdb$parameter_number


::: UserDefinedTypes

SELECT
  F.RDB$FIELD_NAME FIELD_NAME,
  CASE F.RDB$FIELD_TYPE
    WHEN 7 THEN
      CASE F.RDB$FIELD_SUB_TYPE
        WHEN 0 THEN 'SMALLINT'
        WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ', ' || (-F.RDB$FIELD_SCALE) || ')'
        WHEN 2 THEN 'DECIMAL'
      END
    WHEN 8 THEN
      CASE F.RDB$FIELD_SUB_TYPE
        WHEN 0 THEN 'INTEGER'
        WHEN 1 THEN 'NUMERIC('  || F.RDB$FIELD_PRECISION || ', ' || (-F.RDB$FIELD_SCALE) || ')'
        WHEN 2 THEN 'DECIMAL'
      END
    WHEN 9 THEN 'QUAD'
    WHEN 10 THEN 'FLOAT'
    WHEN 12 THEN 'DATE'
    WHEN 13 THEN 'TIME'
    WHEN 14 THEN 'CHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ') '
    WHEN 16 THEN
      CASE F.RDB$FIELD_SUB_TYPE
        WHEN 0 THEN 'BIGINT'
        WHEN 1 THEN 'NUMERIC(' || F.RDB$FIELD_PRECISION || ', ' || (-F.RDB$FIELD_SCALE) || ')'
        WHEN 2 THEN 'DECIMAL'
      END
    WHEN 27 THEN 'DOUBLE'
    WHEN 35 THEN 'TIMESTAMP'
    WHEN 37 THEN 'VARCHAR(' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
    WHEN 40 THEN 'CSTRING' || (TRUNC(F.RDB$FIELD_LENGTH / CH.RDB$BYTES_PER_CHARACTER)) || ')'
    WHEN 45 THEN 'BLOB_ID'
    WHEN 261 THEN 'BLOB SUB_TYPE ' || F.RDB$FIELD_SUB_TYPE
    ELSE 'RDB$FIELD_TYPE: ' || F.RDB$FIELD_TYPE || '?'
  END FIELD_TYPE,
  CH.RDB$CHARACTER_SET_NAME FIELD_CHARSET,
  DCO.RDB$COLLATION_NAME FIELD_COLLATION,
  F.RDB$DEFAULT_SOURCE FIELD_DEFAULT,
  F.RDB$VALIDATION_SOURCE FIELD_CHECK,
  F.RDB$NULL_FLAG AS NULLABLE\n," +
  F.RDB$DESCRIPTION AS DESCRIPTION
FROM RDB$FIELDS F
LEFT OUTER JOIN RDB$CHARACTER_SETS CH ON (CH.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID)
LEFT OUTER JOIN RDB$COLLATIONS DCO ON ((DCO.RDB$COLLATION_ID = F.RDB$COLLATION_ID) AND (DCO.RDB$CHARACTER_SET_ID = F.RDB$CHARACTER_SET_ID))
WHERE (COALESCE(F.RDB$SYSTEM_FLAG, 0) = 0)
and ( ( CH.RDB$CHARACTER_SET_NAME IS NOT NULL AND CH.RDB$CHARACTER_SET_NAME != 'NONE' ) OR
( DCO.RDB$COLLATION_NAME IS NOT NULL AND  DCO.RDB$COLLATION_NAME != 'NONE' ) OR
 F.RDB$DEFAULT_SOURCE IS NOT NULL OR F.RDB$VALIDATION_SOURCE IS NOT NULL OR RDB$NULL_FLAG IS NOT NULL )


::: Indexes

SELECT RDB$RELATION_NAME, RDB$INDEX_NAME
FROM RDB$INDICES
WHERE RDB$UNIQUE_FLAG=1 AND
   (RDB$SYSTEM_FLAG=0 OR RDB$SYSTEM_FLAG IS NULL) AND
EXISTS (SELECT * FROM RDB$RELATION_CONSTRAINTS WHERE RDB$INDEX_NAME=RDB$INDICES.RDB$INDEX_NAME AND RDB$CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')) ORDER BY RDB$RELATION_NAME, RDB$INDEX_NAME